# Loader metadata
modLoader="javafml" # mandatory
loaderVersion="[34.0.9,)" # mandatory
#issueTrackerURL="http://my.issue.tracker/"

# TFC
[[mods]]
    modId="tfc" # mandatory
    version="${file.jarVersion}" #mandatory
    displayName="TerraFirmaCraft" #mandatory
    # A URL to query for updates for this mod. See the JSON update specification <here>
    #updateJSONURL="http://myurl.me/" #optional
    # A URL for the "homepage" for this mod, displayed in the mod UI
    #displayURL="http://example.com/" #optional
    # A file name (in the root of the mod JAR) containing a logo for display
    #logoFile="examplemod.png" #optional
    # A text field displayed in the mod UI
    credits="By AlcatrazEscapee, Disastermoo, Dries007, Bunsan, Claycorp, DavidTriphon, EERussianGuy, Gaelmare, and many others. Based on the original work by Bioxx, Dunk, and Kitty." #optional
    # A text field displayed in the mod UI
    authors="AlcatrazEscapee" #optional
    # The description text for the mod (multi line!) (#mandatory)
    description='''TerraFirmaCraft - The Next Generation'''

# dependencies
[[dependencies.primalwinter]]
    modId="forge"
    mandatory=true
    versionRange="[34.0.9,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.primalwinter]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,)"
    ordering="NONE"
    side="BOTH"